version: "3"
services:
  telegraf:
    image: 'telegraf'
    container_name: 'telegraf'
    depends_on: 
      - influxdb
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    env_file: 
      - telegraf.env
    command: ["telegraf"]
    
  influxdb:
    image: 'influxdb'
    container_name: 'influxdb'
    ports:
      - 8086:8086
    volumes:
      - influxdb-data:/var/lib/influxdb
      - ./influx-samples/:/tmp/samples:ro

volumes:
  influxdb-data:
